### PR TITLE
[*] digits_count = 0 by default

### PR DESCRIPTION
**Pull request by ildarkhasanshin**

### CODE REVIEW

**Comment by Alexey-T** [comment]
4 digits after dot is OK for me. user can change it via config file.

**Comment by ildarkhasanshin** [comment]
5+5=10
5.5+5=10.5
5.55+5=10.55
..

if digits_count = 4 (by default)
5+5=10.0000
..

**Comment by Alexey-T** [comment]
See above reply

**Comment by ildarkhasanshin** [comment]
ok

**Pull request closed without merging**
